---
title: "Mappeoppgave 1 - SOK-1005"
author: "Kandidatnr.: 72"
date: "24 01 2022"
output: pdf_document
---

```{r, warning=FALSE, message=FALSE}
library(data.table)
library(dplyr)
library(ggplot2)
library(lubridate)
library(zoo)
library(tidyverse)
options(scipen=999)
```

### Oppgave 1 

```{r, warning=FALSE, message=FALSE}
df <- fread("http://vortex.nsstc.uah.edu/data/msu/v6.0/tlt/uahncdc_lt_6.0.txt", 
            select=c("Year", "Mo", "Globe"))

df <- slice(df, 1:(n()-1))

df <- as.data.frame(lapply(df, as.numeric))

df$Date <- as.yearmon(paste(df$Year, df$Mo), "%Y %m")

df$Date <- as.Date(df$Date) 

df <- transform(df, rollmean = rollapplyr(Globe, 13, mean, 
                                          partial = TRUE, align = "center"))

# Plot

df %>%
  ggplot(aes(x=Date,y=Globe)) + 
  geom_line(aes(x=Date,y=Globe), colour='darkblue') +
  geom_line(aes(x=Date,y=rollmean), colour='red', size=1.5) +
  geom_point(aes(x=Date,y=Globe), shape = 1, colour='darkblue') + 
  coord_cartesian(xlim = c(as.Date("1980-06-01"), as.Date("2020-01-01"))) +
  geom_hline(yintercept = 0, colour = "wheat4", linetype=1, size=1) +
  theme_minimal() +
  scale_y_continuous(breaks = round(seq(min(df$Globe), 1.0, by = 0.1),1)) +
  scale_x_date(date_breaks="1 year", date_labels="%Y") +
  labs(title = "Latest Global Temps", 
       y = "T Departure from '91-'20 Avg. (deg. C)", x = " ") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  annotate("text", x=as.Date("1987-01-01"), y=0.5, 
           label= "UAH Satellite-Based \n Temperature of the \n Global Lower
           Atmosphere \n (Version 6.0)") +
  annotate("text", x=as.Date("2018-01-01"), y=-0.5, 
           label="December 2021: \n +0.21 deg. C") +
  annotate("text", x=as.Date("2006-01-01"), y=-0.6, 
           label="Running, centered \n 13-month average", colour="red") +
  annotate("segment", x = as.Date("2006-01-01"), 
           xend = as.Date("2009-01-01"), y = -0.5, 
           yend = -0.15, colour = "red") +
  annotate("segment", x = as.Date("2018-01-01"), 
           xend = as.Date("2021-12-01"), y = -0.4, 
           yend = 0.21, colour = "black")

```


\newpage

### Oppgave 2 

```{r, warning=FALSE, message=FALSE}
df1 <- fread(
  "http://vortex.nsstc.uah.edu/data/msu/v6.0/tlt/uahncdc_lt_6.0.txt")
df2 <- fread(
  "http://vortex.nsstc.uah.edu/data/msu/v6.0/tmt/uahncdc_mt_6.0.txt")
df3 <-  fread(
  "http://vortex.nsstc.uah.edu/data/msu/v6.0/ttp/uahncdc_tp_6.0.txt")
df4 <- fread(
  "http://vortex.nsstc.uah.edu/data/msu/v6.0/tls/uahncdc_ls_6.0.txt")

colnames(df1) <- c("Year", "Mo", "Globe_1", "Land1_1", "Ocean1_1", "NH_1",
                   "Land2_1", "Ocean2_1", "SH_1", "Land3_1", "Ocean3_1",
                   "Trpcs_1", "Land4_1", "Ocean4_1", "NoExt_1",  "Land5_1",
                   "Ocean5_1", "SoExt_1",  "Land6_1", "Ocean6_1", "NoPol_1",
                   "Land7_1", "Ocean7_1", "SoPol_1", "Land8_1",
                   "Ocean8_1","USA48_1", "USA49_1",  "AUST_1")

colnames(df2) <- c("Year", "Mo", "Globe_2", "Land1_2", "Ocean1_2", "NH_2",
                   "Land2_2", "Ocean2_2", "SH_2", "Land3_2", "Ocean3_2",
                   "Trpcs_2", "Land4_2", "Ocean4_2", "NoExt_2",  "Land5_2",
                   "Ocean5_2", "SoExt_2",  "Land6_2", "Ocean6_2", "NoPol_2",
                   "Land7_2", "Ocean7_2", "SoPol_2", "Land8_2",
                   "Ocean8_2","USA48_2", "USA49_2",  "AUST_2")

colnames(df3) <- c("Year", "Mo", "Globe_3", "Land1_3", "Ocean1_3", "NH_3",
                   "Land2_3", "Ocean2_3", "SH_3",  "Land3_3", "Ocean3_3",
                   "Trpcs_3", "Land4_3", "Ocean4_3", "NoExt_3",  "Land5_3",
                   "Ocean5_3", "SoExt_3",  "Land6_3", "Ocean6_3", "NoPol_3",
                   "Land7_3", "Ocean7_3", "SoPol_3", "Land8_3",
                   "Ocean8_3","USA48_3", "USA49_3",  "AUST_3")

colnames(df4) <- c("Year", "Mo", "Globe_4", "Land1_4", "Ocean1_4", "NH_4",
                   "Land2_4", "Ocean2_4", "SH_4", "Land3_4", "Ocean3_4",
                   "Trpcs_4", "Land4_4", "Ocean4_4", "NoExt_4",  "Land5_4",
                   "Ocean5_4", "SoExt_4",  "Land6_4", "Ocean6_4", "NoPol_4",
                   "Land7_4", "Ocean7_4", "SoPol_4", "Land8_4", 
                   "Ocean8_4","USA48_4", "USA49_4",  "AUST_4")

df4 <- as.data.frame(lapply(df4, as.character))

join1 <- full_join(df1, df2)
join2 <- full_join(join1, df3)
df <- full_join(join2, df4)
df <- as.data.frame(lapply(df, as.numeric))
df <- slice(df, 1:(n()-1))

df$Date <- as.yearmon(paste(df$Year, df$Mo), "%Y %m")
df$Date <- as.Date(df$Date) 
df$Avg <- (df$NoPol_1+df$NoPol_2+df$NoPol_3+df$NoPol_4)/4
```

\newpage

```{r, warning=FALSE, message=FALSE}
df %>%
  ggplot(aes(x=Date)) + 
  geom_line(aes(y=NoPol_1, colour='Lower Troposphere'), size=1) +
  geom_line(aes(y=NoPol_2, colour='Mid-Troposphere'), size=1) +
  geom_line(aes(y=NoPol_3, colour='Tropopause'), size=1) +
  geom_line(alpha=0.5, aes(y=NoPol_4, colour='Lower Stratosphere'), size=1) +
  geom_line(aes(y=Avg, colour='Snittemp.'), size=0.5) +
  geom_hline(yintercept = 0, colour = "wheat4", linetype=1, size=1) +
  theme_minimal() +
  labs(title = "Temperatur fra 60 til 90 grader nord", 
       y = "T Departure from '91-'20 Avg. (deg. C)", x = " ", color=" ") +
  scale_color_identity() + 
  scale_color_manual(values = c("Lower Troposphere" = "yellow",
                                "Mid-Troposphere" = "black", 
                                "Tropopause" = "red", 
                                "Lower Stratosphere" = "blue",
                                "Snittemp."="green")) +
  theme(legend.position="bottom")
  
```

